# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5946fb1b988268957c75f37228e42c3cbcd8748ae5b56d78b4db4eea453d6d044ef8c8d782612a903c8d0d63c3e8486e158619b9648d459e824f52bde19772f

test:
  secret_key_base: c373a1a24d12d90b83712557e4680716bdc236e06a2dedade84d934ee72887cce4841897ef57fe01cf1dc2395aed1ca0b155d94568776e05cd5423316d225750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: e5946fb1b988268957c75f37228e42c3cbcd8748ae5b56d78b4db4eea453d6d044ef8c8d782612a903c8d0d63c3e8486e158619b9648d459e824f52bde19772f